(define (lookup key table)
  (let ((record (assocc key (cdr table))))
    (if record (cdr record)
      record)))
(define (assocc key records)
  (cond ((null? records) false)
        ((equal? key (caar records)) (car records))
        (else (assocc key (cdr records)))))
(define (insert-table! key value table)
  (let ((record (assocc key (cdr table))))
    (if record
      (set-cdr! record value)
      (set-cdr! table (cons (cons key value) 
                            (cdr table))))))
(define (make-table)
  (list '*table*))
